# Generated by Django 5.0.1 on 2024-01-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancies',
            new_name='organization',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='link',
            field=models.CharField(blank=True, max_length=325, null=True),
        ),
    ]
