# Generated by Django 5.0.1 on 2024-01-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_vacancy_vacancies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
