# Generated by Django 5.0.1 on 2024-01-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_organization_user_user_user_vacancy_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='link',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
